table _dCalendario
	lineageTag: 70df2dab-e9fe-42d0-afa5-b57cb738d421

	measure 'xMD Impacto_Jejum' = ```
			
			
			VAR dat = MAX(_dCalendario[Data])
			
			VAR ultimo_jejum = 
			CALCULATE(
			    MAX(FAT_Jejum[Datas]),
			    FAT_Jejum[Datas] <= dat,
			    ALL(FAT_Jejum)
			)
			
			VAR dias_desde_o_ultimo_jejum = DATEDIFF(ultimo_jejum, dat, DAY)
			
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(ultimo_jejum), "Normal",
			    dias_desde_o_ultimo_jejum = 0, "Jejuando",
			    dias_desde_o_ultimo_jejum <= [Dias_de_Impacto_Jejum], "Pós-Jejum",
			    "Normal"
			)
			    
			```
		lineageTag: b2886f83-abf2-4fbd-8451-91a69d4ef661

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: dccdef78-ddfa-47f3-92b9-242d08bc7608
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 52a5d63e-3c6c-422a-bc99-8adc6663e603
			defaultHierarchy: LocalDateTable_8faf89aa-07df-4e70-978a-d45f5b152b71.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 10e5be46-dd60-4261-b78e-72d953fcdfef
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: ed237b39-7652-4d1e-ab64-49b230e38f69
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: 1856dee3-1b32-4ad4-b73d-1365d4da907a
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 2be2eb9b-64d8-459d-9996-8ed8e2b16a26
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: df8233b7-255b-41e1-b81f-889cc29deda9
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Dia da Semana'
		dataType: int64
		formatString: 0
		lineageTag: 69d33687-75b5-4669-8ed4-c4f1bfb16ead
		summarizeBy: sum
		sourceColumn: Dia da Semana

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia da Semana'
		dataType: string
		lineageTag: 4e84466a-4366-4125-8f6b-241201a8427a
		summarizeBy: none
		sourceColumn: Nome do Dia da Semana

		annotation SummarizationSetBy = Automatic

	column 'xCL Data formatada' = FORMAT([Data], "dd-ddd")
		lineageTag: 0c4df054-a6d7-4c49-9eb6-c0ae270a25fd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DataGrafico
		dataType: dateTime
		formatString: Long Date
		lineageTag: ebfa81f6-a48d-416e-86e9-42ce45ee1b55
		summarizeBy: none
		sourceColumn: DataGrafico

		variation Variation
			isDefault
			relationship: 80aaf0f5-56ab-4659-9721-a3f020692221
			defaultHierarchy: LocalDateTable_90d545ec-3f6b-4bdd-935f-9335440d5167.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Jejuando = ```
			
			IF(
			    ISBLANK(
			        LOOKUPVALUE(
			            FAT_Jejum[Datas],
			            FAT_Jejum[Datas],
			            _dCalendario[Data]
			        )
			    ), 
			    "Normal",
			    "Jejuando"
			)
			```
		lineageTag: d923456d-1236-48fc-8d1d-de870d08e5ed
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Impacto_Jejum = ```
			
			
			VAR dat = _dCalendario[Data]
			
			VAR ultimo_jejum = 
			CALCULATE(
			    MAX(FAT_Jejum[Datas]),
			    FAT_Jejum[Datas] <= dat,
			    ALL(FAT_Jejum)
			)
			
			VAR dias_desde_o_ultimo_jejum = DATEDIFF(ultimo_jejum, dat, DAY)
			
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(ultimo_jejum), "Normal",
			    dias_desde_o_ultimo_jejum = 0, "Jejuando",
			    dias_desde_o_ultimo_jejum <= [Dias_de_Impacto_Jejum], "Pós-Jejum",
			    "Normal"
			)
			```
		lineageTag: f40235f6-3af6-4dcf-bac6-b6e49c35243c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: ac264a5a-e8ce-46f1-b341-11f9b070346f
		summarizeBy: sum
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = Automatic

	column 'Semana do Mês'
		dataType: int64
		formatString: 0
		lineageTag: 8a0aa9e3-3c4c-4c41-b5d0-9a9454514817
		summarizeBy: sum
		sourceColumn: Semana do Mês

		annotation SummarizationSetBy = Automatic

	partition _dCalendario = m
		mode: import
		queryGroup: Auxiliares
		source =
				let
				    Fonte = FAT_Peso[Data],
				    DatasValidas = List.RemoveNulls(Fonte),
				    DataMin = List.Min(DatasValidas),
				    DataMaxOriginal = List.Max(DatasValidas),
				
				    // Ajusta DataMax para ser o último dia do ano da DataMaxOriginal
				    DataMax = #date(Date.Year(DataMaxOriginal), 12, 31),
				
				    ListaDatas = List.Dates(DataMin, Duration.Days(DataMax - DataMin) + 1, #duration(1, 0, 0, 0)),
				
				    TabelaDatas = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Data"}),
				
				    TipoData = Table.TransformColumnTypes(TabelaDatas, {{"Data", type date}}),
				    AddAno = Table.AddColumn(TipoData, "Ano", each Date.Year([Data]), Int64.Type),
				    AddMes = Table.AddColumn(AddAno, "Mês", each Date.Month([Data]), Int64.Type),
				    AddNomeMes = Table.AddColumn(AddMes, "Nome do Mês", each Date.ToText([Data], "MMMM"), type text),
				    AddTrimestre = Table.AddColumn(AddNomeMes, "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
				    AddDia = Table.AddColumn(AddTrimestre, "Dia", each Date.Day([Data]), Int64.Type),
				    AddDiaSemana = Table.AddColumn(AddDia, "Dia da Semana", each Date.DayOfWeek([Data]) + 1, Int64.Type),
				    AddNomeDiaSemana = Table.AddColumn(AddDiaSemana, "Nome do Dia da Semana", each Date.ToText([Data], "dddd"), type text),
				    #"Coluna Duplicada" = Table.DuplicateColumn(AddNomeDiaSemana, "Data", "DataGrafico"),
				    #"Semana do Ano Inserida" = Table.AddColumn(#"Coluna Duplicada", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
				    #"Semana do Mês Inserida" = Table.AddColumn(#"Semana do Ano Inserida", "Semana do Mês", each Date.WeekOfMonth([Data]), Int64.Type)
				in
				    #"Semana do Mês Inserida"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

