table FAT_Peso
	lineageTag: 739d3e59-58aa-4fba-9b32-d2f86a173456

	measure 'Data Anterior' = ```
			
			VAR DataAtual = MAX(FAT_Peso[Data])
			RETURN
			CALCULATE(
			    MAX(FAT_Peso[Data]),
			    FILTER(
			        ALL(FAT_Peso),
			        FAT_Peso[Data] < DataAtual
			    )
			)
			
			```
		formatString: General Date
		lineageTag: cc905144-485c-4678-ba1b-f3f8eeb721fd

	measure 'Peso AVG (D-1)' = ```
			
			VAR DataAtual = MAX(FAT_Peso[Data])
			
			VAR DataAnterior = 
			CALCULATE(
			    MAX(FAT_Peso[Data]),
			    FILTER(
			        ALL(FAT_Peso),
			        FAT_Peso[Data] < DataAtual
			    )
			)
			
			RETURN
			CALCULATE(
			    [Peso AVG], 
			    _dCalendario[Data] = DataAnterior
			)
			```
		lineageTag: 078c87f1-dbd0-4333-8b5e-a15336c28a2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta Δ Peso AVG (#)' = [Peso AVG] - FAT_Peso[Peso AVG (D-1)]
		lineageTag: 891070a4-fa94-41b3-906e-05f2e71e1aed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta Δ Peso AVG (%)' =
			
			DIVIDE(
			    [Peso AVG],
			    [Peso AVG (D-1)],
			    0
			)-1
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 10c6e507-b0ea-4d0a-af37-702770f35a84

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 04a6c072-7690-4b2e-8956-50aad7381577
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Peso
		dataType: double
		lineageTag: 8d209d2d-8987-4228-8918-92b0e10499b6
		summarizeBy: sum
		sourceColumn: Peso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Horário
		dataType: dateTime
		formatString: Long Time
		lineageTag: fc4d6bb7-e3e9-447d-b9b5-2722fc122a69
		summarizeBy: none
		sourceColumn: Horário

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Treino
		dataType: string
		lineageTag: 37a160c3-79d4-4e5d-b79e-c5c7a88a75f3
		summarizeBy: none
		sourceColumn: Treino

		annotation SummarizationSetBy = Automatic

	column DataHora
		dataType: dateTime
		formatString: dd/mm/yy hh:nn
		lineageTag: b280c9ca-407e-4de3-9f6f-9c08d86af493
		summarizeBy: none
		sourceColumn: DataHora

		variation Variation
			isDefault
			relationship: 7dbfd289-3ba1-4f5f-a44b-a0598db91a5f
			defaultHierarchy: LocalDateTable_af909f62-53b7-4b6a-a12a-b2fc9b1cba77.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Período do Dia' =
			
			SWITCH(
			    TRUE(),
			    FAT_Peso[Horário] <= TIME(12,0,0), "Manhã",
			    FAT_Peso[Horário] <= TIME(18,0,0), "Tarde",
			    "Noite"
			)
		lineageTag: 178da8c1-fb63-4bfb-bc1b-bba22b6724b1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'xCL Data Anterior' = ```
			
			
			VAR DataAtual = FAT_Peso[Data]
			
			RETURN
			CALCULATE(
			    MAX(FAT_Peso[Data]),
			    FILTER(
			        ALL(FAT_Peso),
			        FAT_Peso[Data] < DataAtual
			    )
			)
			
			```
		formatString: General Date
		lineageTag: 56c47fef-c21b-4fc2-aa42-631b1430a886
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 9d724f12-00ae-4456-9ee4-7ca6b34b8e94
			defaultHierarchy: LocalDateTable_fca13d4e-0c92-4bcf-a681-39dbe7d12836.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'xCL Peso Anterior' = ```
			
			
			VAR DataAtual = FAT_Peso[Data]
			
			VAR DataAnterior = FAT_Peso[xCL Data Anterior]
			
			RETURN
			CALCULATE(
			    [Peso AVG], 
			    FILTER(
			        ALL(FAT_Peso),
			        FAT_Peso[Data] = DataAnterior
			    )
			)
			```
		lineageTag: a51ea80e-e0fb-447b-97cd-91505ba674e4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'xCL Delta Peso Médio (#)' = ```
			
			IF(
			    ISBLANK(FAT_Peso[xCL Peso Anterior]), 
			    0, 
			    FAT_Peso[Peso] - FAT_Peso[xCL Peso Anterior]
			)
			```
		formatString: 0.00
		lineageTag: 4fe0906c-79e6-4dae-8c1b-99570582aabc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition FAT_Peso = m
		mode: import
		queryGroup: FATs
		source =
				let
				    Fonte = Csv.Document(
				        Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQsotOBIQLZD1HNZROsSqg0TU_A9XYZu3DUpqvpKIq6R317OOmIeI-drhC1jGJx8ipXxRPFlzzEyqgq/pub?gid=0&single=true&output=csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data", type date}, {"Peso", type number}, {"Horário", type time}, {"Treino", type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [Data] <> null and [Data] <> ""),
				    #"Data e Hora Mescladas Inseridas" = Table.AddColumn(#"Linhas Filtradas", "DataHora", each [Data] & [Horário], type datetime)
				in
				    #"Data e Hora Mescladas Inseridas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

