table FAT_Jejum
	lineageTag: 548a2957-8522-4c96-91b7-c7ec5d3fb647

	measure Dias_de_Impacto_Jejum = 2
		formatString: 0
		lineageTag: e2ec60cc-d914-4dd5-b290-d4cadc2759de

	column 'Data Início'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 695b0959-e45d-436e-8c2a-d324cae3414c
		summarizeBy: none
		sourceColumn: Data Início

		variation Variation
			isDefault
			relationship: 7f32a451-d359-40be-b5be-36365c830ab5
			defaultHierarchy: LocalDateTable_e21cd110-e9f5-4dfa-b3b0-690e29f33318.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Hora Início'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5a6567a7-1ec0-4030-acf7-500e2362f8b6
		summarizeBy: none
		sourceColumn: Hora Início

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Período (h)'
		dataType: double
		lineageTag: a4594735-0a7a-4051-b606-ed5dff694341
		summarizeBy: sum
		sourceColumn: Período (h)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data Hora Início'
		dataType: dateTime
		formatString: General Date
		lineageTag: fac019f3-7e9b-4006-8a5d-1dcc9fb271e4
		summarizeBy: none
		sourceColumn: Data Hora Início

		variation Variation
			isDefault
			relationship: 55e2336a-6993-444d-b658-7c35afbef217
			defaultHierarchy: LocalDateTable_dc0389f5-3054-4f5c-b0b9-e77fd63f72d5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data Hora Fim'
		dataType: dateTime
		formatString: General Date
		lineageTag: 09e027a7-d893-42be-92c7-f8c92a7167a3
		summarizeBy: none
		sourceColumn: Data Hora Fim

		variation Variation
			isDefault
			relationship: bec82356-9c0e-4cfb-83f2-ed0d83bba071
			defaultHierarchy: LocalDateTable_1befbc04-7ef6-4dd7-a908-e51b7fd51d18.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Datas
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb6134ec-507c-4ac9-a727-e02dfcf8194f
		summarizeBy: none
		sourceColumn: Datas

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FAT_Jejum = m
		mode: import
		queryGroup: FATs
		source = ```
				let
				    Fonte = Csv.Document(
				        Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQsotOBIQLZD1HNZROsSqg0TU_A9XYZu3DUpqvpKIq6R317OOmIeI-drhC1jGJx8ipXxRPFlzzEyqgq/pub?gid=909800497&single=true&output=csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Linhas Filtradas" = Table.SelectRows(#"Cabeçalhos Promovidos", each [Data Início] <> null and [Data Início] <> ""),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"Data Início", type date}, {"Hora Início", type time}, {"Período (h)", type number}}),
				    #"Data e Hora Mescladas Inseridas" = Table.AddColumn(#"Tipo Alterado", "Data Hora Início", each [Data Início] & [Hora Início], type datetime),
				    #"Personalização Adicionada" = Table.AddColumn(#"Data e Hora Mescladas Inseridas", "Data Hora Fim", each Duration.From([#"Período (h)"]/24)+[#"Data Hora Início"], type datetime),
				
				    // 1. Adiciona uma nova coluna "ListaDatas" com a lista de datas (tipo date) entre as duas colunas datetime
				    AddListaDatas = Table.AddColumn(
				        #"Personalização Adicionada",
				        "Datas",
				        each 
				            let
				                inicio = DateTime.Date([#"Data Hora Início"]),
				                fim = DateTime.Date([#"Data Hora Fim"]),
				                dias = Duration.Days(fim - inicio) + 1,
				                lista = List.Dates(inicio, dias, #duration(1,0,0,0))
				            in
				                lista
				    ),
				
				    // 2. Expande essa lista para ter uma linha para cada data
				    ExpandeDatas = Table.ExpandListColumn(AddListaDatas, "Datas"),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(ExpandeDatas,{{"Datas", type date}})
				in
				    #"Tipo Alterado2"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

