table FAT_Jejum
	lineageTag: 548a2957-8522-4c96-91b7-c7ec5d3fb647

	measure Dias_de_Impacto_Jejum = 2
		formatString: 0
		lineageTag: e2ec60cc-d914-4dd5-b290-d4cadc2759de

	measure 'xMD BLANK Jejum' = IF(MIN(FAT_Jejum[Datas]), [xMD Aux Peso MAX Constant])
		formatString: 0
		lineageTag: f85166e3-57bf-4ebe-8115-fcfdb22df19e

	measure 'Tempo Jejum Médio (h)' = AVERAGE(FAT_Jejum[Período do jejum])
		lineageTag: dc0e485b-adf8-4a22-9a23-5e0e44fc3a61

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Datas
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb6134ec-507c-4ac9-a727-e02dfcf8194f
		summarizeBy: none
		sourceColumn: Datas

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Data
		dataType: dateTime
		formatString: General Date
		lineageTag: c4d79522-1cf6-424b-8f5f-174bc1dc60ec
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 645517b0-5419-4d44-9d69-6ddbb876ae91
			defaultHierarchy: LocalDateTable_11c4c236-366a-4e96-a77b-2f10a58fabd0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Período do jejum'
		dataType: double
		lineageTag: ce3300b7-f278-407b-ada4-579f5a69798a
		summarizeBy: sum
		sourceColumn: Período do jejum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data Fim'
		dataType: dateTime
		formatString: General Date
		lineageTag: e82d5022-c437-4074-be2a-523130930273
		summarizeBy: none
		sourceColumn: Data Fim

		variation Variation
			isDefault
			relationship: 0d5e343a-658a-46be-97e8-7e5eb417cfb7
			defaultHierarchy: LocalDateTable_84968592-1ceb-4997-a2ac-98e3e2fc247e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition FAT_Jejum = m
		mode: import
		queryGroup: FATs
		source = ```
				let
				    Fonte = Origem_Jejum,
				    #"Linhas Filtradas1" = Table.SelectRows(Fonte, each ([Tipo de Registro] = "Jejum")),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Filtradas1",{"Data", "Período do jejum", "Data Fim"}),
				    // 1. Adiciona uma nova coluna "ListaDatas" com a lista de datas (tipo date) entre as duas colunas datetime
				    AddListaDatas = Table.AddColumn(
				        #"Outras Colunas Removidas",
				        "Datas",
				        each 
				            let
				                inicio = DateTime.Date([Data]),
				                fim = DateTime.Date([#"Data Fim"]),
				                dias = Duration.Days(fim - inicio) + 1,
				                lista = List.Dates(inicio, dias, #duration(1,0,0,0))
				            in
				                lista
				    ),
				
				    // 2. Expande essa lista para ter uma linha para cada data
				    ExpandeDatas = Table.ExpandListColumn(AddListaDatas, "Datas"),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(ExpandeDatas,{{"Datas", type date}})
				in
				    #"Tipo Alterado2"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

